update cntools

diff --git a/src/pool/cntools/cnode/scripts/env b/src/pool/cntools/cnode/scripts/env
--- a/src/pool/cntools/cnode/scripts/env
+++ b/src/pool/cntools/cnode/scripts/env
@@ -6,9 +6,10 @@
 # Leave as is if unsure              #
 ######################################
 
-#CNODEBIN="${HOME}/.cabal/bin/cardano-node"             # Override automatic detection of cardano-node executable
-#CCLI="${HOME}/.cabal/bin/cardano-cli"                  # Override automatic detection of cardano-cli executable
-#CNCLI="${HOME}/.cargo/bin/cncli"                       # Override automatic detection of executable (https://github.com/AndrewWestberg/cncli)
+#USESYSVARS="N"                                         # Whether to use environment variable from shell session for CNODE_HOME
+#CNODEBIN="${HOME}/.local/bin/cardano-node"             # Override automatic detection of cardano-node executable
+#CCLI="${HOME}/.local/bin/cardano-cli"                  # Override automatic detection of cardano-cli executable
+#CNCLI="${HOME}/.local/bin/cncli"                       # Override automatic detection of executable (https://github.com/AndrewWestberg/cncli)
 #CNODE_HOME="/opt/cardano/cnode"                        # Override default CNODE_HOME path (defaults to /opt/cardano/cnode)
 #CNODE_PORT=6000                                        # Set node port
 #CONFIG="${CNODE_HOME}/files/config.json"               # Override automatic detection of node config path
@@ -32,11 +33,12 @@
 #TG_CHAT_ID=""                                          # https://cardano-community.github.io/guild-operators/Scripts/sendalerts
 #TIMEOUT_LEDGER_STATE=300                               # Timeout in seconds for querying and dumping ledger-state
 #IP_VERSION=4                                           # The IP version to use for push and fetch, valid options: 4 | 6 | mix (Default: 4)
-ENABLE_KOIOS=Y                                         # (Y|N) Enable KOIOS API. If disabled, local node queries will be used instead with increased system resource requirements (default Y)
-#KOIOS_API="https://api.koios.rest/api/v0/"             # Koios API for blockchain queries instead of local cli lookup.
-                                                        # Leave commented for automatic network detection between MainNet, TestNet and Guild network.
+#ENABLE_KOIOS=Y                                         # (Y|N) Enable KOIOS API. If disabled, local node queries will be used instead with increased system resource requirements (default Y)
+#KOIOS_API="https://api.koios.rest/api/v0"              # Koios API for blockchain queries instead of local cli lookup.
+                                                        # Leave commented for automatic network detection between MainNet, Preview, Preprod or Guild network.
                                                         # https://www.koios.rest/
 #DBSYNC_QUERY_FOLDER="${CNODE_HOME}/files/dbsync/queries" # [advanced feature] Folder containing DB-Sync chain analysis queries
+#G_ACCOUNT="cardano-community"             # Override default github repository if you forked project
 
 #WALLET_FOLDER="${CNODE_HOME}/priv/wallet"              # Root folder for Wallets
 #POOL_FOLDER="${CNODE_HOME}/priv/pool"                  # Root folder for Pools
@@ -61,6 +63,7 @@ ENABLE_KOIOS=Y                                         # (Y|N) Enable KOIOS API.
 #POOL_HOTKEY_SK_FILENAME="hot.skey"
 #POOL_COLDKEY_VK_FILENAME="cold.vkey"
 #POOL_COLDKEY_SK_FILENAME="cold.skey"
+#POOL_HW_COLDKEY_SK_FILENAME="cold.hwsfile"
 #POOL_OPCERT_COUNTER_FILENAME="cold.counter"
 #POOL_OPCERT_FILENAME="op.cert"
 #POOL_VRF_VK_FILENAME="vrf.vkey"
@@ -74,8 +77,6 @@ ENABLE_KOIOS=Y                                         # (Y|N) Enable KOIOS API.
 #ASSET_POLICY_VK_FILENAME="policy.vkey"                 # Standardized names for all multi-asset related files
 #ASSET_POLICY_SK_FILENAME="policy.skey"
 #ASSET_POLICY_SCRIPT_FILENAME="policy.script"           # File extension '.script' mandatory
-#ASSET_POLICY_ID_FILENAME="policy.id"
-
 
 
 CNODE_HOME="/cntools/cnode"                             # Override default CNODE_HOME path (defaults to /opt/cardano/cnode)
@@ -112,10 +113,6 @@ fi
 ######################################
 # Do NOT modify code below           #
 ######################################
-
-# Initialise/Set offline mode prior to calling functions
-OFFLINE_MODE='N'
-[[ $1 = "offline" ]] && OFFLINE_MODE='Y'
 
 # Description : Check if provided file exists
 #             : $1 = File (with path) to check
@@ -195,9 +192,6 @@ checkUpdate() {
   [[ -n $5 ]] && URL="${URL_RAW}/scripts/$5" || URL="${URL_RAW}/scripts/cnode-helper-scripts"
   URL_DOCS="${URL_RAW}/docs/Scripts"
   if curl -s -f -m ${CURL_TIMEOUT} -o "${dname}/${fname}".tmp "${URL}/${fname}" 2>/dev/null; then
-
-    # replace default CNODE with custom name if needed
-    [[ ${CNODE_VNAME} != cnode ]] && sed -e "s@/opt/cardano/[c]node@/opt/cardano/${CNODE_VNAME}@g" -e "s@[C]NODE_HOME@${CNODE_VNAME_UPPERCASE}_HOME@g" -i "${dname}/${fname}".tmp
 
     # make sure script exist, else just rename
     [[ ! -f "${dname}/${fname}" ]] && mv -f "${dname}/${fname}".tmp "${dname}/${fname}" && chmod +x "${dname}/${fname}" && return 0
@@ -314,10 +308,10 @@ joinArray() {
 # Description : Generate asset id according to CIP-14 standard
 #               https://github.com/cardano-foundation/CIPs/pull/64
 #             : $1 = hex-encoded policy ID
-#             : $2 = ASCII formatted asset name
+#             : $2 = hex-encoded asset name
 getAssetIDBech32() {
   { ! cmdAvailable "bech32" || ! cmdAvailable "b2sum"; } && return 1
-  printf "$(echo -n $1 | sed 's/../\\x&/g')%s" "$2" | b2sum -l 160 -b | cut -d' ' -f 1 | bech32 asset
+  printf "$(echo -n $1$2 | sed 's/../\\x&/g')" | b2sum -l 160 -b | cut -d' ' -f 1 | bech32 asset
 }
 
 # Description : Convert a normal 1 byte ASCII string to hex (alnum chars)
@@ -326,7 +320,7 @@ asciiToHex() {
   local ascwrd=$1
   [[ -z ${ascwrd} ]] && return
   for ((i=0;i<${#ascwrd};i++)); do
-    printf %02x \'${ascwrd:$i:1}
+    printf %02x \'"${ascwrd:$i:1}"
   done
 }
 
@@ -338,7 +332,7 @@ hexToAscii() {
   [[ -z ${hexstr} ]] && return
   (( hexcnt % 2 != 0 )) && return
   for ((i=0;i<${#hexstr};i=i+2)); do
-    printf "\x${hexstr:$i:2}"
+    [[ ${hexstr:$i:2} = "00" ]] && printf "\x20" || printf "\x${hexstr:$i:2}" # 00 = NUL char, special case handling
   done
 }
 
@@ -736,7 +730,7 @@ slotInterval() {
 }
 
 # Description : Identify current era and set variables accordingly
-# TODO: Track progress of https://github.com/input-output-hk/cardano-node/pull/4135 to see if era identifier can be removed in a future release. 
+# TODO: Track progress of https://github.com/input-output-hk/cardano-node/pull/4135 to see if era identifier can be removed in a future release.
 getEraIdentifier() {
   NETWORK_ERA=$(${CCLI} query tip ${NETWORK_IDENTIFIER} 2>/dev/null | jq -r '.era //empty')
   case ${NETWORK_ERA} in
@@ -752,8 +746,6 @@ getEraIdentifier() {
   return 0
 }
 
-[[ ${0} != '-bash' ]] && PARENT=$(dirname $0) || PARENT="$(pwd)" # If sourcing at terminal, $0 would be "-bash" , which is invalid. Thus, fallback to present working directory
-
 telegramSend() {
   if [[ -z "${TG_BOT_TOKEN}" ]] || [[ -z "${TG_CHAT_ID}" ]]; then
     echo "Warn: to use the telegramSend function you must first set the bot and chat id in the env file"
@@ -764,6 +756,8 @@ telegramSend() {
 }
 
 set_default_vars() {
+
+  [[ "${USESYSVARS}" != "Y" ]] && unset CNODE_HOME
   [[ $(basename $0 2>/dev/null) = "cnode.sh" ]] && OFFLINE_MODE='Y' # for backwards compatibility
   [[ $(basename $0 2>/dev/null) = "topologyUpdater.sh" ]] && OFFLINE_MODE='Y' # for backwards compatibility
 
@@ -778,7 +772,7 @@ set_default_vars() {
      date () { gdate "$@"; }
   fi
   [[ -z ${CURL_TIMEOUT} ]] && CURL_TIMEOUT=10
-  [[ -z "${CNODE_HOME}" ]] && CNODE_HOME=/opt/cardano/cnode
+  [[ -z "${CNODE_HOME}" ]] && CNODE_HOME="$(readlink -f ${PARENT}/..)"
   CNODE_NAME="$(basename ${CNODE_HOME})"
   CNODE_VNAME=$(tr '[:upper:]' '[:lower:]' <<< ${CNODE_NAME//_HOME/})
   CNODE_VNAME_UPPERCASE=$(tr '[:lower:]' '[:upper:]' <<< ${CNODE_VNAME})
@@ -815,6 +809,7 @@ set_default_vars() {
   [[ -z ${POOL_HOTKEY_SK_FILENAME} ]] && POOL_HOTKEY_SK_FILENAME="hot.skey"
   [[ -z ${POOL_COLDKEY_VK_FILENAME} ]] && POOL_COLDKEY_VK_FILENAME="cold.vkey"
   [[ -z ${POOL_COLDKEY_SK_FILENAME} ]] && POOL_COLDKEY_SK_FILENAME="cold.skey"
+  [[ -z ${POOL_HW_COLDKEY_SK_FILENAME} ]] && POOL_HW_COLDKEY_SK_FILENAME="cold.hwsfile"
   [[ -z ${POOL_OPCERT_COUNTER_FILENAME} ]] && POOL_OPCERT_COUNTER_FILENAME="cold.counter"
   [[ -z ${POOL_OPCERT_FILENAME} ]] && POOL_OPCERT_FILENAME="op.cert"
   [[ -z ${POOL_VRF_VK_FILENAME} ]] && POOL_VRF_VK_FILENAME="vrf.vkey"
@@ -844,12 +839,17 @@ set_default_vars() {
   NC='\e[0m'
 }
 
+[[ ${0} != '-bash' ]] && PARENT=$(dirname $0) || PARENT="$(pwd)" # If sourcing at terminal, $0 would be "-bash" , which is invalid. Thus, fallback to present working directory
+# Initialise/Set offline mode prior to calling functions
+OFFLINE_MODE='N'
+[[ $1 = "offline" ]] && OFFLINE_MODE='Y'
+
 set_default_vars
 
 [[ -z "${CCLI}" ]] && CCLI=$(command -v cardano-cli)
 if [[ -z "${CCLI}" ]]; then
-  if [[ -f "${HOME}/.cabal/bin/cardano-cli" ]]; then
-    export PATH="${HOME}/.cabal/bin":$PATH
+  if [[ -f "${HOME}/.local/bin/cardano-cli" ]]; then
+    export PATH="${HOME}/.local/bin":$PATH
     CCLI=$(command -v cardano-cli)
   else
     echo "You do not have a cardano-cli binary available in \$PATH."
@@ -862,17 +862,17 @@ if [[ -z "${CNODEBIN}" ]]; then
   if [[ -f "$(dirname ${CCLI})"/cardano-node ]]; then
     CCLIPARENT="$(dirname ${CCLI})" && export PATH="${CCLIPARENT}":$PATH
     CNODEBIN="$(dirname ${CCLI})"/cardano-node
-  elif [[ -f "${HOME}/.cabal/bin/cardano-node" ]]; then
-    export PATH="${HOME}/.cabal/bin":$PATH
+  elif [[ -f "${HOME}/.local/bin/cardano-node" ]]; then
+    export PATH="${HOME}/.local/bin":$PATH
     CNODEBIN=$(command -v cardano-node)
-  elif [[ ${OFFLINE_MODE} = "Y" ]]; then
+  elif [[ ${OFFLINE_MODE} = "N" ]]; then
     echo "You do not have a cardano-node binary available in \$PATH."
     return 1
   fi
 fi
 
 if [[ -z "${CNCLI}" ]]; then
-  CNCLI=$(command -v cncli) || CNCLI="${HOME}/.cargo/bin/cncli"
+  CNCLI=$(command -v cncli) || CNCLI="${HOME}/.local/bin/cncli"
 fi
 
 [[ -f /usr/local/lib/libsodium.so ]] && export LD_LIBRARY_PATH=/usr/local/lib:"${LD_LIBRARY_PATH}" && PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:"${PKG_CONFIG_PATH}"
@@ -907,12 +907,12 @@ if command -v "ss" &>/dev/null; then
 elif command -v "lsof" &>/dev/null; then
   use_lsof='Y'
 else
-  echo -e "'ss' and fallback 'lsof' commands are missing, please install using latest prereqs.sh script or with your packet manager of choice.\nhttps://command-not-found.com/ss can be used to check package name to install.\n"
+  echo -e "'ss' and fallback 'lsof' commands are missing, please install using latest guild-deploy.sh script or with your packet manager of choice.\nhttps://command-not-found.com/ss can be used to check package name to install.\n"
   return 1
 fi
 
 if ! command -v "jq" &>/dev/null; then
-  echo -e "'jq' command is missing, please install using latest prereqs.sh script of with your packet manager of choice.\nhttps://command-not-found.com/ss can be used to check package name to install.\n"
+  echo -e "'jq' command is missing, please install using latest guild-deploy.sh script of with your packet manager of choice.\nhttps://command-not-found.com/ss can be used to check package name to install.\n"
   return 1
 fi
 
@@ -1010,8 +1010,8 @@ if [[ -n "${CNODE_PID}" ]]; then
 fi
 
 node_version="$(${CCLI} version | head -1 | cut -d' ' -f2)"
-if ! versionCheck "1.35.2" "${node_version}"; then
-  echo -e "\nGuild scripts has now been upgraded to support cardano-node 1.35.2 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.\n\n"
+if ! versionCheck "1.35.5" "${node_version}"; then
+  echo -e "\nGuild scripts has now been upgraded to support cardano-node 1.35.5 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.\n\n"
   return 1
 fi
 
@@ -1035,7 +1035,7 @@ read_genesis
 
 [[ ${NWMAGIC} == "764824073" ]] && NETWORK_IDENTIFIER="--mainnet" || NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}"
 case ${NWMAGIC} in
-  764824073) 
+  764824073)
     NETWORK_NAME="Mainnet"
     SHELLEY_TRANS_EPOCH=208
     [[ -z ${KOIOS_API} ]] && KOIOS_API="https://api.koios.rest/api/v0" ;;
@@ -1043,7 +1043,7 @@ case ${NWMAGIC} in
     NETWORK_NAME="PreProd"
     SHELLEY_TRANS_EPOCH=4
     [[ -z ${KOIOS_API} ]] && KOIOS_API="https://preprod.koios.rest/api/v0";;
-  141) 
+  141)
     NETWORK_NAME="Guild"
     SHELLEY_TRANS_EPOCH=2
     [[ -z ${KOIOS_API} ]] && KOIOS_API="https://guild.koios.rest/api/v0" ;;
@@ -1051,11 +1051,7 @@ case ${NWMAGIC} in
     NETWORK_NAME="Preview"
     SHELLEY_TRANS_EPOCH=0
     [[ -z ${KOIOS_API} ]] && KOIOS_API="https://preview.koios.rest/api/v0" ;;
-  1097911063) # To be retired soon
-    NETWORK_NAME="Testnet"
-    SHELLEY_TRANS_EPOCH=74
-    [[ -z ${KOIOS_API} ]] && KOIOS_API="https://testnet.koios.rest/api/v0" ;;
-  *) 
+  *)
     NETWORK_NAME="Custom"
     [[ -z ${SHELLEY_TRANS_EPOCH} ]] && SHELLEY_TRANS_EPOCH=0
 esac
