cleanup

diff --git a/chart/lidonation.com/templates/cronjob.activevoteplans.yaml b/chart/lidonation.com/templates/cronjob.activevoteplans.yaml
--- a/chart/lidonation.com/templates/cronjob.activevoteplans.yaml
+++ b/chart/lidonation.com/templates/cronjob.activevoteplans.yaml
@@ -93,6 +93,24 @@ spec:
                 - name: GENESIS_PATH
                   value: /leader1stuff/artifacts/block0.bin
             - name: query-api
+              image: alpine:latest
+              imagePullPolicy: IfNotPresent
+              volumeMounts:
+                - name: "{{ $.Chart.Name }}-catalyst-utils-pv"
+                  mountPath: /leader1stuff
+              command:
+                - "/bin/sh"
+                - "-c"
+                - |
+                  sleep 4m
+                  curl http://127.0.0.1:10000/api/v0/vote/active/plans
+                  if [[ $? -ne 0 ]]; then
+                    echo "Failed to get the active vote plans."
+                    exit 1
+                  fi
+                  curl http://127.0.0.1:10000/api/v0/vote/active/plans > /leader1stuff/activevotingplans.proposals.json
+                  kill -9 $(pidof jormungandr)
+            - name: query-api
               image: bitnami/kubectl:1.27.5-debian-11-r17
               imagePullPolicy: IfNotPresent
               volumeMounts:
@@ -102,15 +120,9 @@ spec:
                 - "/bin/sh"
                 - "-c"
                 - |
-                  sleep 5m
-                  curl http://127.0.0.1:10000/api/v0/vote/active/plans
-                  if [[ $? -ne 0 ]]; then
-                    echo "Failed to get the active vote plans."
-                    exit 1
-                  fi
-                  curl http://127.0.0.1:10000/api/v0/vote/active/plans > /leader1stuff/activevotingplans.proposals.json
+                  apk add curl
+                  sleep 7m
                   kubectl cp /leader1stuff/activevotingplans.proposals.json $(kubectl get pods -l service=lidolovelace-web-fpm --field-selector=status.phase=Running -o=jsonpath='{.items[0].metadata.name}'):/var/www/storage/app/catalyst/activevotingplans.proposals.json
-                  kill -9 $(pidof jormungandr)
           imagePullSecrets:
             - name: {{ .Values.image.pullSecret }}
           restartPolicy: Never    
